### ISSUE TITLE
Privacy Statement/Policy?

### ISSUE THREAD

**Issue by ifreund** [Ameobea/spotifytrack#26]
It would be good to have an explanation of exactly what data is stored on users by spotify track as well as a way to delete it if desired.

**Comment by Ameobea** [comment]
The only personal data that Spotifytrack stores is your Spotify username as well as the tokens generated by Spotify which allow Spotifytrack to get access to your top tracks and artists.

**No other personal data like date of birth, email address, IP address, etc. is collected or stored.**

The main data that Spotifytrack stores is your music listening data.  It stores snapshots of your top tracks and artists over time and uses that to build all of the charts, graphs and other visualizations on the site.

If you want your account deleted with all associated data, you can reach out to me directly via email or any other method and provide your Spotify username.  I'll delete everything for your user.
